ALTER TABLE "DateIdea" ADD COLUMN "planAPrepItems" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "DateIdea" ADD COLUMN "planBPrepItems" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "PlannedDate" ADD COLUMN "planAPrepBoard" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "PlannedDate" ADD COLUMN "planBPrepBoard" TEXT NOT NULL DEFAULT '[]';
